.TH "API version" 3 "Tue May 22 2012" "Version 1.5a1git0de3530c33a9c221969822ab079fb4d0dde6387c" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
API version \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHWLOC_API_VERSION\fP   0x00010500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI " unsigned \fBhwloc_get_api_version\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HWLOC_API_VERSION   0x00010500"
.PP
Indicate at build time which hwloc API version is being used. 
.SH "Function Documentation"
.PP 
.SS " unsigned hwloc_get_api_version (void)"
.PP
Indicate at runtime which hwloc API version was used at build time. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
